// Tibetan UI strings, keyed by their English label. Kept in its own module so
// the component files that use it stay Fast-Refresh-friendly (a file that
// exports components should only export components).
export const TIBETAN_LABELS: Record<string, string> = {
  // Menu bar
  'File': 'ཡིག་ཆ།',
  'Edit': 'རྩོམ་སྒྲིག',
  'View': 'ལྟ་བཤེར།',
  'Insert': 'བསྒར་འཛུད།',
  'Format': 'རྣམ་གཞག',
  'Table': 'རེའུ་མིག',
  'Help': 'རོགས་རམ།',
  // File menu
  'New': 'གསར་བཟོ།',
  'Open...': 'ཁ་ཕྱེ།',
  'Open Recent': 'ཉེ་ལམ།',
  'No recent files': 'ཡིག་ཆ་མེད།',
  'Clear Recent': 'གཙང་བཟོ།',
  'Save': 'ཉར་ཚགས།',
  'Save As...': 'གཞན་ཉར།',
  'Export PDF': 'PDF ཕྱིར་འདོན།',
  'Export EPUB': 'EPUB ཕྱིར་འདོན།',
  'Print': 'པར་འདེབས།',
  // Edit menu
  'Undo': 'ཕྱིར་འཐེན།',
  'Redo': 'བསྐྱར་བྱེད།',
  'Cut': 'གཏུབ།',
  'Copy': 'ཕབ་བཤུས།',
  'Paste': 'སྦྱར།',
  'Select All': 'ཚང་མ་འདེམས།',
  'Find & Replace': 'འཚོལ་བརྗེ།',
  // View menu
  'Zoom In': 'ཆེ་རུ།',
  'Zoom Out': 'ཆུང་རུ།',
  'Reset Zoom': 'ཆེ་ཆུང་སོར་ཆུད།',
  'Focus Mode': 'དམིགས་གཏད།',
  'Typewriter Mode': 'ཡིག་འཕྲུལ།',
  'Reading Mode': 'ཀློག་ཐབས།',
  'Document Outline': 'ས་བཅད།',
  'Dictionary': 'ཚིག་མཛོད།',
  // Insert menu
  'Image': 'པར་རིས།',
  'Horizontal Rule': 'ཐིག་ཕྲེང་།',
  'Page Break': 'ཤོག་ངོས་གསར།',
  'Footnote': 'ཞབས་མཆན།',
  'Code Block': 'ཨང་རྟགས།',
  'Special Characters': 'ཡིག་རྟགས།',
  // Format menu
  'Bold': 'སྦོམ་པོ།',
  'Italic': 'གཡོན་འཁྱོག',
  'Underline': 'འོག་ཐིག',
  'Strikethrough': 'དཀྲོག་ཐིག',
  'Superscript': 'སྟེང་ཡིག',
  'Subscript': 'འོག་ཡིག',
  'Heading 1': 'མགོ་བྱང་ ༡',
  'Heading 2': 'མགོ་བྱང་ ༢',
  'Heading 3': 'མགོ་བྱང་ ༣',
  'Bullet List': 'རྩེ་རྟགས།',
  'Numbered List': 'ཨང་རིམ།',
  'Blockquote': 'དྲངས་ཚིག',
  'Indent': 'ནང་སྐུད།',
  'Outdent': 'ཕྱིར་སྐུད།',
  'Line Spacing': 'ཐིག་བར།',
  'Clear Formatting': 'རྣམ་གཞག་གཙང་བཟོ།',
  // Line spacing submenu
  'Single (1.0)': 'གཅིག (1.0)',
  'Double (2.0)': 'གཉིས (2.0)',
  'Default': 'སོར་བཞག',
  // Table menu
  'Insert Table': 'རེའུ་མིག་བསྒར།',
  'Add Row Above': 'སྟེང་ལ་སྟར།',
  'Add Row Below': 'འོག་ལ་སྟར།',
  'Delete Row': 'སྟར་སུབ།',
  'Add Column Left': 'གཡོན་ལ་སྟར།',
  'Add Column Right': 'གཡས་ལ་སྟར།',
  'Delete Column': 'སྟར་སུབ།',
  'Merge Cells': 'ཁང་མིག་སྡེབ།',
  'Split Cell': 'ཁང་མིག་གཏོར།',
  'Delete Table': 'རེའུ་མིག་སུབ།',
  // View menu
  'Settings': 'སྒྲིག་འགོད།',
  // Help menu
  'Help & FAQ': 'རོགས་རམ་དང་དྲི་བ།',
  'Typing Tibetan (Practice)': 'བོད་ཡིག་སྦྱོང་བརྡར།',
  'Wylie Reference': 'ཝ་ལིའི་གཞུང་།',
  'TCRC Reference': 'TCRC མཐེབ་གཞོང་།',
  'Keyboard Shortcuts': 'མཐེབ་གནོན།',
  'About TermaType': 'གཏེར་མ་ཡིག་སྦྱོར་སྐོར།',
  // Dictionary sidebar
  'Tibetan-English Dictionary': 'བོད་དབྱིན་ཚིག་མཛོད།',
  'Search Tibetan or English...': 'བོད་ཡིག་གམ་དབྱིན་ཡིག་འཚོལ།',
  'Search': 'འཚོལ།',
  'Searching...': 'འཚོལ་བཞིན།',
  'No results found.': 'འབྲས་བུ་མ་རྙེད།',
  'Open Dictionary ›': 'ཚིག་མཛོད་ཁ་ཕྱེ། ›',
  // Status bar
  'words': 'ཚིག',
  'chars': 'ཡིག་འབྲུ',
  'min': 'སྐར་མ',
  'pg': 'ཤོག་ངོས',
  'Modified': 'བཟོ་བཅོས།',
  'Local': 'ས་གནས།',
  'Untitled': 'མིང་མེད།',
  'New document': 'ཡིག་ཆ་གསར་བཟོ།',
  'Saved just now': 'ད་ལྟ་ཉར་ཚགས།',
  'New document tab': 'ཡིག་ཆ་གསར་པ།',
}
